application: feed-stuypulse
version: 1
runtime: python27
api_version: 1
threadsafe: true
inbound_services:
- warmup

skip_files:
- ^(.*/)?.*\.pyc
- .*\.DS_Store

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  expiration: 30d
- url: /(apple-touch-icon.*\.(png))
  static_files: static/\1
  upload: static/(apple-touch-icon.*\.png)
  expiration: 30d
- url: /static
  static_dir: static
- url: /images
  static_dir: static/images
  expiration: 14d
- url: /css
  static_dir: static/css
  expiration: 7d
- url: /js
  static_dir: static/js
  expiration: 7d
- url: /hangout.*
  script: feed.hangout.application
- url: /admin.*
  script: feed.admin.application
  login: admin
- url: /.*
  script: feed.main.application
