application: feed-stuypulse
version: 1
runtime: python27
api_version: 1
threadsafe: true
inbound_services:
- warmup

skip_files:
- ^(.*/)?.*\.pyc

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: feed/static/favicon.ico
  upload: feed/static/favicon\.ico
  expiration: 30d
- url: /(apple-touch-icon.*\.(png))
  static_files: feed/static/\1
  upload: feed/static/(apple-touch-icon.*\.png)
  expiration: 30d
- url: /static
  static_dir: feed/static
  expiration: 7d
- url: /hangout
  script: feed.hangout.application
- url: /admin.*
  script: feed.admin.application
- url: /.*
  script: feed.main.application
